Us24 update connexion verif champs
WildCodeSchool-2024-02/JS-lyon-0224-P3-globalmeals pull request #38
Opened 2024-06-26 14:17 UTC by djibmsa

2024-06-26 14:22 UTC, LoicLeg69 approved these changes
ok

2024-06-26 14:55 UTC, wildmatthieu requested changes

2024-06-26 14:55 UTC, wildmatthieu commented on client/src/components/connexion/connexion.jsx
> +              type={showPassword ? "text" : "password"}
explicit condition : 
`showPassword === ___ ? ... `

2024-06-26 14:55 UTC, wildmatthieu commented on client/src/components/connexion/connexion.jsx
> +              {showPassword ? "🙈" : "👁️"}
explicit condition : 
`showPassword === ___ ? ... `

2024-06-26 14:55 UTC, wildmatthieu commented on client/src/components/connexion/connexion.jsx
> +        {isSubmitted && <p>Connexion soumise avec succès !</p>}
explicit condition : 
`isSubmitted === ___ && ... `

2024-06-27 09:41 UTC, LoicLeg69 commented on client/src/components/connexion/connexion.jsx
> +              type={showPassword ? "text" : "password"}
fait

2024-06-27 09:41 UTC, LoicLeg69 commented on client/src/components/connexion/connexion.jsx
> +              {showPassword ? "🙈" : "👁️"}
fait

2024-06-27 09:42 UTC, LoicLeg69 commented on client/src/components/connexion/connexion.jsx
> +        {isSubmitted && <p>Connexion soumise avec succès !</p>}
fait

2024-06-27 10:02 UTC, merged